export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""
plugins=(git zsh-autosuggestions zsh-syntax-highlighting fzf)
source $ZSH/oh-my-zsh.sh

eval "$(starship init zsh)"

export PATH="$PATH:/opt/nvim/bin"
export PATH="$HOME/.local/bin:$PATH"
export JAVA_HOME=/usr/lib/jvm/default
export EDITOR="nvim"
export VISUAL="nvim"

# Aliases
alias v="nvim"
alias vim="nvim"
alias lg="lazygit"
alias ll="ls -la --color=auto"
alias cat="bat"
alias update="yay -Syu"
alias grep="grep --color=auto"
alias hyprconf="nvim ~/.config/hypr/hyprland.conf"
alias waybconf="nvim ~/.config/waybar/config.jsonc"
alias zshconf="nvim ~/.zshrc"
alias reload="source ~/.zshrc"
alias wallpaper="wallpaper-picker"
alias docker-up="docker compose up -d"
alias docker-down="docker compose down"

export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude .git"
export FZF_DEFAULT_OPTS="--height 40% --border"
